apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb-v1
  labels:
    name: influxdb
spec:
  replicas: 1
  selector:
    name: influxdb
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      containers:
      - name: influxdb
        image: rochacon/influxdb
        ports:
        - containerPort: 8083
          protocol: TCP
        - containerPort: 8086
          protocol: TCP
